# Generated by Django 3.2.4 on 2021-06-10 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedadew', '0006_property_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
    ]
